<?php

abstract class Vehicle {

	abstract public function drive();
	
	public function where() {
		echo "anywhere.";
	}
}
 


/* NOT OK! you can not instantiate an abstract class 
$vehicle = new Vehicle();
$vehicle->drive();
$vehicle->where(); */


class Car extends Vehicle {
	
  public function drive() {
 		echo "A mile of highway will take you a mile, a mile of runway will take you ";
  }
} 
 
/* OK */
$car = new Car();
$car->drive();
$car->where(); 




echo "<br><br>";
echo "<i>The above output is generated by the code below:</i><br>";
highlight_file( __FILE__ ); 
?>